# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-21 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=64)),
                ('g_price', models.FloatField(default=0)),
                ('g_market_price', models.FloatField(default=0)),
                ('g_unit', models.CharField(max_length=32)),
                ('g_detail', models.TextField()),
                ('g_img', models.CharField(max_length=128)),
                ('g_bar_code', models.CharField(max_length=64)),
                ('g_store_num', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTypeOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsTypeTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
                ('g_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodstypetwos', to='FruitServer.GoodsTypeOne')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.GoodsTypeTwo'),
        ),
    ]
