# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FruitServer', '0002_auto_20191022_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_adds', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1)),
                ('is_select', models.BooleanField(default=True)),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content', models.TextField()),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='FruitUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=32, unique=True)),
                ('f_password', models.CharField(max_length=256)),
                ('f_age', models.IntegerField(default=1)),
                ('f_sex', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_forbidden', models.BooleanField(default=False)),
                ('f_email', models.CharField(max_length=64, unique=True)),
                ('f_register_date', models.DateTimeField(auto_now_add=True)),
                ('f_icon', models.CharField(max_length=128, null=True)),
                ('is_activite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=64)),
                ('g_price', models.FloatField(default=0)),
                ('g_market_price', models.FloatField(default=0)),
                ('g_unit', models.CharField(max_length=32)),
                ('g_detail', models.TextField()),
                ('g_img', models.CharField(max_length=128)),
                ('g_bar_code', models.CharField(max_length=64)),
                ('g_store_num', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gradememory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_grade', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.IntegerField(default=0)),
                ('o_price', models.FloatField(default=0)),
                ('o_order_time', models.DateTimeField(auto_now_add=True)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_add', models.CharField(max_length=100)),
                ('o_adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_price', models.IntegerField(default=10)),
                ('t_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.Order')),
                ('t_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='g_ordergoods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.OrderGoods'),
        ),
        migrations.AddField(
            model_name='comments',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser'),
        ),
        migrations.AddField(
            model_name='cart',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser'),
        ),
        migrations.AddField(
            model_name='address',
            name='a_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitGP2.FruitUser'),
        ),
    ]
